/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voting.application;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.JScrollPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author Admin
 */
public class AdminPage extends javax.swing.JFrame {
    static int firstSubmitFlag = 0; //variable to check if its the first submission of the session to make sure session_list table is inserted to only once.
    static int last_sessionID; //to store last session Id from table
    static int new_sessionID;  //to calculate and store current sessions ID by incrementing last session id by 1
    public static String adminId; //to store the adminId gathered from the args[] from previous frame
    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
        //SETTING UP VISUALS
        back.setIcon(new ImageIcon(new ImageIcon("backkk.png").getImage().getScaledInstance(45,35,Image.SCALE_DEFAULT)));
        mcqPanel.setVisible(false);
        Descriptive.setSelected(true);
        finishSession.setVisible(false);
        sessionCode.setVisible(false);
        //Calculating new session ID
        //Adding categories to QuesCategory list
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/VoteApp","root","root");
            Statement st = con.createStatement();
            String query1 = "SELECT Distinct Category from Session_Details;";
            ResultSet rs1 = st.executeQuery(query1);
            
            while(rs1.next())
            {
                String item = rs1.getString("Category");
                QuesCategory.addItem(item);
            }
            
            String query2 = "SELECT MAX(SessionID) from Session_list;";
            ResultSet rs2 = st.executeQuery(query2);
            rs2.next();
            last_sessionID = Integer.parseInt(rs2.getString("MAX(SessionID)"));
            new_sessionID = last_sessionID+1;
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        quesArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        submitQues = new javax.swing.JButton();
        QuesCategory = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        finishSession = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        new_category = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Descriptive = new javax.swing.JRadioButton();
        Mcq = new javax.swing.JRadioButton();
        TrueFalse = new javax.swing.JRadioButton();
        mcqPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        optionA = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        optionB = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        optionC = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        optionD = new javax.swing.JTextField();
        sessionCode = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        viewButton = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");
        setPreferredSize(new java.awt.Dimension(900, 770));

        quesArea.setColumns(20);
        quesArea.setRows(5);
        jScrollPane1.setViewportView(quesArea);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Type your Question here:");

        submitQues.setText("Submit Question");
        submitQues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitQuesActionPerformed(evt);
            }
        });

        QuesCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuesCategoryActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Category:");

        finishSession.setText("Finish Session");
        finishSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishSessionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("CREATE");

        jLabel8.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 0));
        jLabel8.setText("VIEW");

        jLabel9.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 153));
        jLabel9.setText("QUESTIONS");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Add a new Category:");

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Type:");

        buttonGroup1.add(Descriptive);
        Descriptive.setText("Descriptive");
        Descriptive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DescriptiveMouseClicked(evt);
            }
        });

        buttonGroup1.add(Mcq);
        Mcq.setText("MCQ");
        Mcq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                McqMouseClicked(evt);
            }
        });

        buttonGroup1.add(TrueFalse);
        TrueFalse.setText("True/False");
        TrueFalse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrueFalseMouseClicked(evt);
            }
        });

        jLabel10.setText("Option A.");

        jLabel11.setText("Option B.");

        jLabel12.setText("Option C.");

        jLabel13.setText("Option D.");

        javax.swing.GroupLayout mcqPanelLayout = new javax.swing.GroupLayout(mcqPanel);
        mcqPanel.setLayout(mcqPanelLayout);
        mcqPanelLayout.setHorizontalGroup(
            mcqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mcqPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mcqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mcqPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(optionC))
                    .addGroup(mcqPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(optionA, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(mcqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mcqPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(optionB, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mcqPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(optionD)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        mcqPanelLayout.setVerticalGroup(
            mcqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mcqPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mcqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(optionA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(optionB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(mcqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(optionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(optionD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        sessionCode.setText("Current Session Code: ");

        jLabel15.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 204, 0));
        jLabel15.setText("&");

        viewButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(QuesCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(new_category, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(add))
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(viewButton)
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel6)
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel15)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel8)
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(42, 42, 42)
                                        .addComponent(Descriptive)
                                        .addGap(44, 44, 44)
                                        .addComponent(Mcq)
                                        .addGap(44, 44, 44)
                                        .addComponent(TrueFalse)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mcqPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(submitQues)
                .addGap(179, 179, 179)
                .addComponent(sessionCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(finishSession)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel15))
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QuesCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Descriptive)
                    .addComponent(Mcq)
                    .addComponent(TrueFalse))
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mcqPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishSession, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitQues, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sessionCode))
                .addGap(109, 109, 109))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        //ADDing new category if not already exists
        String new_cat = new_category.getText();
        if(!new_cat.equals("") && ((DefaultComboBoxModel)QuesCategory.getModel()).getIndexOf(new_cat) == -1)
        {
            QuesCategory.addItem(new_cat);
        }
        new_category.setText("");
    }//GEN-LAST:event_addActionPerformed

private boolean checkIfEmpty(){
    if(quesArea.getText().equals(""))
        return true;
    else if(Mcq.isSelected()){
        String opA = optionA.getText(), opB = optionB.getText(), opC = optionC.getText(), opD = optionD.getText();
        if(opA.equals("")||opB.equals("") || opC.equals("")|| opD.equals(""))
            return true;
    }
    return false;
} 

    private void submitQuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitQuesActionPerformed

        String[] buttonSelect = new String[3]; //keep track of which radiobutton is selected
        int i; //keep track of which radiobutton is selected
        if(Descriptive.isSelected()){
            buttonSelect[0] = "TRUE";
            i = 0;
        }
        else if(Mcq.isSelected()){
            buttonSelect[1] = "TRUE";
            i = 1;
        }
        else{
            buttonSelect[2] = "TRUE";
            i = 2;
        }
        
        String ques_cat = (String)QuesCategory.getSelectedItem();
        if(checkIfEmpty())
            JOptionPane.showMessageDialog(null, "Please fill all the necessary text fields.");
        else{
        //If it is the first submission of the session
        if(firstSubmitFlag == 0){
            firstSubmitFlag = 1;
            try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/VoteApp","root","root");
            Statement st = con.createStatement();
            //SINCE IT IS THE FIRST TIME SUBMITTING IN THE NEW SESSION WE HAVE TO UPDATE THE SESSION LIST TABLE ONCE AND ALSO UPDATE THE SESSION DETAILS TABLE
            String query1 = "INSERT INTO session_list VALUES(" + new_sessionID + ", " + adminId + ");" ;
            int rs1 = st.executeUpdate(query1);
            
            String query2 = "INSERT INTO session_details VALUES(" + new_sessionID + ", '" + ques_cat + "', '" +  buttonSelect[0] + "', '" +  buttonSelect[1] + "', '" +  buttonSelect[2] + "');";
            int rs2 = st.executeUpdate(query2);
            JOptionPane.showMessageDialog(null, "Successful");
            //CREATE AN ENTRY IN ATTEMPTED TABLE FOR THE NEW SESSION
            String newColumn = "S"+new_sessionID;
            String addEntry = "ALTER TABLE Attempted ADD COLUMN " + newColumn + " char(3) DEFAULT 'No';";
            int resAdd = st.executeUpdate(addEntry);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        }
        //If a question is already added to the session and we are now adding more questions 
        else{
              try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/VoteApp","root","root");
            Statement st = con.createStatement();
            String column = i == 0 ? "Descriptive" : i == 1 ? "MCQ" : "TrueFalse";
            //WE NEED TO UPDATE THE SESSION'S DETAILS IF THE NEXT QUESTION IS OF A DIFFERENT TYPE
            String query = "UPDATE session_details SET " + column + "=" + "'TRUE'" + " WHERE sessionID=" + new_sessionID + ";";
            int rs = st.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Successful");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }  
        }
        //THIS STEP IS COMMON TO ALL AND INCLUDES THE INSERTION OF QUESTION TO ITS RESPECTIVE TYPE TABLE
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/VoteApp","root","root");
            Statement st = con.createStatement();
            String query;
            String question = quesArea.getText();
            if(i == 0){
                query = "INSERT INTO type_descriptive VALUES(" + new_sessionID + ", '" + question + "', " + 0 + ");";
            }
            else if(i == 1){
               String opA = optionA.getText(), opB = optionB.getText(), opC = optionC.getText(), opD = optionD.getText();
               query = "INSERT INTO type_mcq VALUES(" + new_sessionID + ", '" + question + "', '" + opA + "', '" +
                        opB + "', '" + opC + "', '" + opD + "', " + 0 + ");";
            }
            else{
                query = "INSERT INTO type_truefalse VALUES(" + new_sessionID + ", '" + question + "', " + 0 + ");";
            }
            
            int rs = st.executeUpdate(query);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        } 
        sessionCode.setVisible(true);
        sessionCode.setText("Current Session Code: " + new_sessionID);
        //CLEARING THE TEXTFIELDS 
        quesArea.setText("");
        optionA.setText("");
        optionB.setText("");
        optionC.setText("");
        optionD.setText("");
        finishSession.setVisible(true);
        QuesCategory.setEnabled(false);
        }
    }//GEN-LAST:event_submitQuesActionPerformed

    private void DescriptiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescriptiveMouseClicked
       mcqPanel.setVisible(false);
    }//GEN-LAST:event_DescriptiveMouseClicked

    private void McqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_McqMouseClicked
       mcqPanel.setVisible(true);
    }//GEN-LAST:event_McqMouseClicked

    private void TrueFalseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrueFalseMouseClicked
       mcqPanel.setVisible(false);
    }//GEN-LAST:event_TrueFalseMouseClicked

    private void finishSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishSessionActionPerformed
       //RESET VALUES
       last_sessionID = new_sessionID;
       new_sessionID = new_sessionID + 1;
       firstSubmitFlag = 0;
       quesArea.setText("");
       optionA.setText("");
       optionB.setText("");
       optionC.setText("");
       optionD.setText("");
       sessionCode.setText("Current Session:");
       Descriptive.setSelected(true);
       finishSession.setVisible(false);
       QuesCategory.setEnabled(true);
    }//GEN-LAST:event_finishSessionActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        //OPEN THE VIEW WINDOW
        String[] id = new String[1];
        id[0] = adminId;
        View.main(id);
        this.setVisible(false);
    }//GEN-LAST:event_viewButtonActionPerformed

    private void QuesCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuesCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuesCategoryActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        //GO BACK TO LOGIN PAGE
        Login openLogin = new Login();
        openLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        adminId = args[0];
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               /* if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }*/
               UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Descriptive;
    private javax.swing.JRadioButton Mcq;
    private javax.swing.JComboBox<String> QuesCategory;
    private javax.swing.JRadioButton TrueFalse;
    private javax.swing.JButton add;
    private javax.swing.JLabel back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton finishSession;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel mcqPanel;
    private javax.swing.JTextField new_category;
    private javax.swing.JTextField optionA;
    private javax.swing.JTextField optionB;
    private javax.swing.JTextField optionC;
    private javax.swing.JTextField optionD;
    private javax.swing.JTextArea quesArea;
    private javax.swing.JLabel sessionCode;
    private javax.swing.JButton submitQues;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
