package voting.application;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.Properties;
/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
         initComponents();
         //SETTING UP VISUALS
         logo.setIcon(new ImageIcon(new ImageIcon("logo.jpg").getImage().getScaledInstance(125, 125, Image.SCALE_DEFAULT)));
         user.setIcon(new ImageIcon(new ImageIcon("userlogo.png").getImage().getScaledInstance(69, 52, Image.SCALE_DEFAULT)));
         pass.setIcon(new ImageIcon(new ImageIcon("pass.png").getImage().getScaledInstance(69, 52, Image.SCALE_DEFAULT)));
         IdField.setForeground(Color.gray);
         IdField.setText("Username");
         PswrdField.setForeground(Color.GRAY);
         PswrdField.setText("-----Password----");
         UserEmpty.setVisible(false);
         PswrdEmpty.setVisible(false);
         Invalid.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JLabel();
        IdField = new javax.swing.JTextField();
        pass = new javax.swing.JLabel();
        PswrdField = new javax.swing.JPasswordField();
        signIn = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        UserEmpty = new javax.swing.JLabel();
        PswrdEmpty = new javax.swing.JLabel();
        Invalid = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        forgotPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VoteApp- Login ");
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(700, 600));

        user.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/application/userlogo.png"))); // NOI18N
        user.setMaximumSize(new java.awt.Dimension(69, 52));
        user.setMinimumSize(new java.awt.Dimension(69, 52));
        user.setPreferredSize(new java.awt.Dimension(69, 52));

        IdField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        IdField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IdFieldMouseClicked(evt);
            }
        });
        IdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdFieldActionPerformed(evt);
            }
        });
        IdField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IdFieldKeyPressed(evt);
            }
        });

        pass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/application/pass.png"))); // NOI18N
        pass.setMaximumSize(new java.awt.Dimension(69, 55));
        pass.setMinimumSize(new java.awt.Dimension(69, 55));
        pass.setPreferredSize(new java.awt.Dimension(69, 55));

        PswrdField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PswrdField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PswrdFieldMouseClicked(evt);
            }
        });
        PswrdField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PswrdFieldKeyPressed(evt);
            }
        });

        signIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        signIn.setText("Sign-In");
        signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/application/logo.jpg"))); // NOI18N
        logo.setMaximumSize(new java.awt.Dimension(100, 100));
        logo.setMinimumSize(new java.awt.Dimension(100, 100));
        logo.setPreferredSize(new java.awt.Dimension(125, 125));

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 0));
        jLabel3.setText("VoteApp");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Welcome to GEU Voting Application.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Create");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("View");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("Rate");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Questions.");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText(",");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText(",");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("and");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("your");

        UserEmpty.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        UserEmpty.setForeground(new java.awt.Color(204, 0, 0));
        UserEmpty.setText("User Id field cannot be empty.");

        PswrdEmpty.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        PswrdEmpty.setForeground(new java.awt.Color(204, 0, 0));
        PswrdEmpty.setText("Password Field cannot be empty.");

        Invalid.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        Invalid.setForeground(new java.awt.Color(204, 0, 0));
        Invalid.setText("Id and Password do not match. Please try again.");

        forgotPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        forgotPassword.setForeground(new java.awt.Color(51, 51, 255));
        forgotPassword.setText("Forgot Password...?");
        forgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPasswordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel5)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IdField, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                            .addComponent(UserEmpty)
                            .addComponent(PswrdField)
                            .addComponent(PswrdEmpty))))
                .addGap(0, 144, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(signIn)
                        .addGap(123, 123, 123)
                        .addComponent(forgotPassword))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(Invalid)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)))
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Invalid)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(UserEmpty)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PswrdField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(PswrdEmpty)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signIn)
                    .addComponent(forgotPassword))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdFieldActionPerformed

    private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed
        /*
        Make sure Username and Password are not empty
        */
        if(IdField.getText().equals(""))
            UserEmpty.setVisible(true);

        else if(PswrdField.getText().equals(""))
            PswrdEmpty.setVisible(true);

        else{
        try{
            /*
            Comparing and matching the entered username,password with the one registered in the database
            */
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/VoteApp","root","root");
            Statement st = con.createStatement();
            String sql = "SELECT Password, Type from Users where Id = " + IdField.getText() + " ;";
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            String original_pswrd = rs.getString("Password");
            String type = rs.getString("Type");
            String pswrd = new String(PswrdField.getPassword());
            
            if(original_pswrd.equals(pswrd))
            {
                String id[] = new String[1];
                id[0] = IdField.getText();
                if(type.equals("A"))
                {
                    //If user has Admin priveleges then open AdminPage
                    AdminPage.main(id);
                    this.dispose();
                }
                else
                {
                    //If user is a student then open student's page.
                    StudentPage.main(id);
                    this.dispose();
                }
            }
            else
                Invalid.setVisible(true);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Username does not exist.");
        }
      }
        
    }//GEN-LAST:event_signInActionPerformed

    private void IdFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdFieldKeyPressed
        // TODO add your handling code here:
        UserEmpty.setVisible(false);
    }//GEN-LAST:event_IdFieldKeyPressed

    private void PswrdFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PswrdFieldKeyPressed
        // TODO add your handling code here:
        PswrdEmpty.setVisible(false);
    }//GEN-LAST:event_PswrdFieldKeyPressed

    private void IdFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdFieldMouseClicked
        // TODO add your handling code here:
        if(IdField.getText().equals("Username"))
            IdField.setText("");
    }//GEN-LAST:event_IdFieldMouseClicked

    private void PswrdFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PswrdFieldMouseClicked
        // TODO add your handling code here:
        if(PswrdField.getText().equals("-----Password----"))
            PswrdField.setText("");
    }//GEN-LAST:event_PswrdFieldMouseClicked

    private void forgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordMouseClicked
        //FUNCTION TO RESET PASSWORD USING JAVA MAIL API
        /*
        Display a window confirming user's Id.
        */
        JFrame f;
        f = new JFrame();
        String id = JOptionPane.showInputDialog(f, "Enter your USERID to receive\na password reset through email.");
        String receiverEmail = "";
        /*
        Extracting the user's mail id registered in the database
        */
        try{
           
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/VoteApp","root","root");
            Statement st = con.createStatement();
            String sql = "SELECT Email FROM Users WHERE Id = " + id + " ;";
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            receiverEmail = rs.getString("Email");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        /*
        Generating a  new random unique Password using the self built UniquePassword class
        */
        UniquePassword generator = new UniquePassword();
        String newPassword = generator.generatePassowrd();
        /*
        Assigning value to senderEmail and password
        */
        final String senderEmail = "yuvrajjoshi31@gmail.com";
        final String password = "123*yuvraj*123";
        /*
        Using JavaMail API to send email using Gmail SMTP server
        */
        /**
	   Outgoing Mail (SMTP) Server
	   requires TLS or SSL: smtp.gmail.com (use authentication)
	   Use Authentication: Yes
	   Port for TLS/STARTTLS: 587 //default port
	 */
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");    //enable authentication
        props.put("mail.smtp.starttls.enable", "true"); //enable STARTLLS
        props.put("mail.smtp.host", "smtp.gmail.com"); //SMTP host: protocol to send mails over TCP/IP
        props.put("mail.smtp.port", "587"); //TLS Port for security
        
         /*
        Creating a Session object which stores the host name, username, password etc.
        */
        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(senderEmail, password);
                    }
                });
        //BODY OF EMAIL
        try {
            /*
            Creating message
            */
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(senderEmail));
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(receiverEmail));
            message.setSubject("Vote App Password Reset");
            message.setText("Your new password is " +
                    newPassword);
            /*
            Sending the message
            */
            Transport.send(message);
 
        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
        /*
        Updating the database with the new generated password.
        */
        try{
           
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/VoteApp","root","root");
            Statement st = con.createStatement();
            String sql = "UPDATE Users SET Password = '" + newPassword + "' WHERE Id = " + id + ";";
            int rs = st.executeUpdate(sql);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_forgotPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdField;
    private javax.swing.JLabel Invalid;
    private javax.swing.JLabel PswrdEmpty;
    private javax.swing.JPasswordField PswrdField;
    private javax.swing.JLabel UserEmpty;
    private javax.swing.JLabel forgotPassword;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel pass;
    private javax.swing.JButton signIn;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
